### ISSUE TITLE
release link needed

### ISSUE THREAD

**Issue by GordonRBurgess** [woodsywisdom/peak-project#27]
Please add a URL for your heroku release.

**Comment by woodsywisdom** [comment]
I'm a bit confused as to where you mean.  I've got a live link to the
heroku release in the readme and it's on my scorecard and in interview db.
Was there somewhere else I could have it?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by GordonRBurgess** [comment]
This one is one me - it's pretty easy to see where it is.  Thanks, Will!
